server:
  port: 8006

spring:
  application:
    name: cloud-consumer-consul-payment
  # consul注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}