server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #表示将自己注册进EurekaServer
    fetch-registry: true # 是否从EurekaServer抓取自己的注册信息，默认为true，单节点无所谓，集群必须设置为TRUE才能配合Ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port} #Eureka注册中心上的status中显示的名称
    prefer-ip-address: true #访问路径显示IP地址信息

cloud:
  server:
    payment-name: http://CLOUD-PAYMENT-SERVICE