server:
  port: 7001
eureka:
  instance:
    hostname: 192.168.31.237 #eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示本身就是注册中心，维护服务实例，并不需要去检索服务
    service-url:
      # 设置与Eureka Server交互的地址，查询服务和注册服务需要依赖此地址
      # 单机版就是注册自己
      defaultZone: http://192.168.31.237:7001/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/
#  server:
#    # 关闭自我保护机制，保证不可用服务及时被剔除
#    enable-self-preservation: false
#    # 设置默认离线时间从90秒 变为 2秒
#    eviction-interval-timer-in-ms: 2000

